import 'package:flutter/material.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';
import 'package:uuid/uuid.dart';
import 'habit.dart';

const _uuid = Uuid();

/// Pre-defined habit templates for quick creation
class HabitTemplate {
  final String id;
  final String title;
  final String description;
  final HabitCategory category;
  final IconData icon;
  final Color color;
  final HabitDifficulty difficulty;
  final HabitTimeBlock timeBlock;
  final int weeklyTarget;
  final int monthlyTarget;
  final List<String> tags;
  final String? suggestedReminderTime;

  const HabitTemplate({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.icon,
    required this.color,
    this.difficulty = HabitDifficulty.medium,
    this.timeBlock = HabitTimeBlock.anytime,
    this.weeklyTarget = 5,
    this.monthlyTarget = 20,
    this.tags = const [],
    this.suggestedReminderTime,
  });

  /// Convert template to Habit
  Habit toHabit() {
    return Habit(
      id: _uuid.v4(), // Generate new unique ID for each habit instance
      title: title,
      description: description,
      color: color,
      icon: icon,
      category: category,
      timeBlock: timeBlock,
      difficulty: difficulty,
      weeklyTarget: weeklyTarget,
      monthlyTarget: monthlyTarget,
      tags: tags,
    );
  }
}

/// Pre-defined habit templates library
class HabitTemplates {
  static final List<HabitTemplate> all = [
    // Health Category
    HabitTemplate(
      id: 'template_water',
      title: 'Drink Water',
      description: 'Stay hydrated throughout the day',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.drop,
      color: const Color(0xFF4A90E2),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 7,
      monthlyTarget: 30,
      tags: ['health', 'hydration', 'wellness'],
      suggestedReminderTime: '09:00',
    ),
    HabitTemplate(
      id: 'template_exercise',
      title: 'Exercise',
      description: 'Physical activity for 30+ minutes',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.barbell,
      color: const Color(0xFFE74C3C),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 4,
      monthlyTarget: 16,
      tags: ['health', 'fitness', 'exercise'],
      suggestedReminderTime: '07:00',
    ),
    HabitTemplate(
      id: 'template_sleep',
      title: 'Sleep 8 Hours',
      description: 'Get quality sleep for better health',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.moon,
      color: const Color(0xFF6C5CE7),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 7,
      monthlyTarget: 30,
      tags: ['health', 'sleep', 'recovery'],
      suggestedReminderTime: '22:00',
    ),
    HabitTemplate(
      id: 'template_walk',
      title: 'Take a Walk',
      description: '10,000 steps or 30-minute walk',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.footprints,
      color: const Color(0xFF00B894),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['health', 'walking', 'movement'],
    ),

    // Productivity Category
    HabitTemplate(
      id: 'template_reading',
      title: 'Read',
      description: 'Read for 30+ minutes',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.bookOpen,
      color: const Color(0xFF9B59B6),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['productivity', 'learning', 'reading'],
      suggestedReminderTime: '20:00',
    ),
    HabitTemplate(
      id: 'template_journal',
      title: 'Journal',
      description: 'Write in your journal',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.notebook,
      color: const Color(0xFFF39C12),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['productivity', 'reflection', 'writing'],
      suggestedReminderTime: '21:00',
    ),
    HabitTemplate(
      id: 'template_planning',
      title: 'Daily Planning',
      description: 'Plan your day ahead',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.calendarCheck,
      color: const Color(0xFF3498DB),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['productivity', 'planning', 'organization'],
      suggestedReminderTime: '08:00',
    ),
    HabitTemplate(
      id: 'template_deepwork',
      title: 'Deep Work',
      description: '2+ hours of focused work',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.target,
      color: const Color(0xFF2ECC71),
      difficulty: HabitDifficulty.hard,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 4,
      monthlyTarget: 16,
      tags: ['productivity', 'focus', 'work'],
      suggestedReminderTime: '09:00',
    ),

    // Learning Category
    HabitTemplate(
      id: 'template_language',
      title: 'Language Practice',
      description: 'Practice a new language',
      category: HabitCategory.learning,
      icon: PhosphorIconsRegular.translate,
      color: const Color(0xFFE67E22),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['learning', 'language', 'education'],
    ),
    HabitTemplate(
      id: 'template_coding',
      title: 'Code Practice',
      description: 'Practice coding or programming',
      category: HabitCategory.learning,
      icon: PhosphorIconsRegular.code,
      color: const Color(0xFF1ABC9C),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['learning', 'coding', 'programming'],
    ),
    HabitTemplate(
      id: 'template_online_course',
      title: 'Online Course',
      description: 'Complete a lesson or module',
      category: HabitCategory.learning,
      icon: PhosphorIconsRegular.graduationCap,
      color: const Color(0xFF8E44AD),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 4,
      monthlyTarget: 16,
      tags: ['learning', 'education', 'course'],
    ),

    // Mindfulness Category
    HabitTemplate(
      id: 'template_meditation',
      title: 'Meditate',
      description: '10+ minutes of meditation',
      category: HabitCategory.mindfulness,
      icon: PhosphorIconsRegular.yinYang,
      color: const Color(0xFF7F8C8D),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['mindfulness', 'meditation', 'peace'],
      suggestedReminderTime: '07:30',
    ),
    HabitTemplate(
      id: 'template_gratitude',
      title: 'Gratitude Practice',
      description: 'Write 3 things you\'re grateful for',
      category: HabitCategory.mindfulness,
      icon: PhosphorIconsRegular.heart,
      color: const Color(0xFFE91E63),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 7,
      monthlyTarget: 30,
      tags: ['mindfulness', 'gratitude', 'positivity'],
      suggestedReminderTime: '20:30',
    ),
    HabitTemplate(
      id: 'template_breathing',
      title: 'Breathing Exercise',
      description: '5 minutes of breathing exercises',
      category: HabitCategory.mindfulness,
      icon: PhosphorIconsRegular.wind,
      color: const Color(0xFF00BCD4),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['mindfulness', 'breathing', 'relaxation'],
    ),

    // Wellness Category
    HabitTemplate(
      id: 'template_skincare',
      title: 'Skincare Routine',
      description: 'Complete your skincare routine',
      category: HabitCategory.wellness,
      icon: PhosphorIconsRegular.sparkle,
      color: const Color(0xFFFF6B9D),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 7,
      monthlyTarget: 30,
      tags: ['wellness', 'self-care', 'skincare'],
      suggestedReminderTime: '21:00',
    ),
    HabitTemplate(
      id: 'template_stretching',
      title: 'Stretching',
      description: '10+ minutes of stretching',
      category: HabitCategory.wellness,
      icon: PhosphorIconsRegular.barbell,
      color: const Color(0xFF95A5A6),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['wellness', 'flexibility', 'recovery'],
      suggestedReminderTime: '08:00',
    ),
    HabitTemplate(
      id: 'template_meal_prep',
      title: 'Meal Prep',
      description: 'Prepare healthy meals',
      category: HabitCategory.wellness,
      icon: PhosphorIconsRegular.forkKnife,
      color: const Color(0xFFF1C40F),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.afternoon,
      weeklyTarget: 2,
      monthlyTarget: 8,
      tags: ['wellness', 'nutrition', 'cooking'],
    ),

    // Creativity Category
    HabitTemplate(
      id: 'template_drawing',
      title: 'Draw or Sketch',
      description: 'Creative drawing practice',
      category: HabitCategory.creativity,
      icon: PhosphorIconsRegular.pencilSimple,
      color: const Color(0xFFE74C3C),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 4,
      monthlyTarget: 16,
      tags: ['creativity', 'art', 'drawing'],
    ),
    HabitTemplate(
      id: 'template_music',
      title: 'Music Practice',
      description: 'Practice an instrument or music',
      category: HabitCategory.creativity,
      icon: PhosphorIconsRegular.musicNote,
      color: const Color(0xFF9B59B6),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['creativity', 'music', 'practice'],
    ),
    HabitTemplate(
      id: 'template_writing',
      title: 'Creative Writing',
      description: 'Write creatively',
      category: HabitCategory.creativity,
      icon: PhosphorIconsRegular.penNib,
      color: const Color(0xFF34495E),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 4,
      monthlyTarget: 16,
      tags: ['creativity', 'writing', 'expression'],
    ),
    
    // Additional Health Habits
    HabitTemplate(
      id: 'template_yoga',
      title: 'Yoga Session',
      description: '30 minutes of yoga practice',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.leaf,
      color: const Color(0xFF00B894),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 4,
      monthlyTarget: 16,
      tags: ['health', 'yoga', 'flexibility'],
      suggestedReminderTime: '07:00',
    ),
    HabitTemplate(
      id: 'template_stretching',
      title: 'Morning Stretch',
      description: '10 minutes of stretching',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.heart,
      color: const Color(0xFF6C5CE7),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['health', 'flexibility', 'mobility'],
      suggestedReminderTime: '07:30',
    ),
    HabitTemplate(
      id: 'template_vitamins',
      title: 'Take Vitamins',
      description: 'Daily vitamin supplement',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.forkKnife,
      color: const Color(0xFFF39C12),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 7,
      monthlyTarget: 30,
      tags: ['health', 'nutrition', 'wellness'],
      suggestedReminderTime: '08:00',
    ),
    HabitTemplate(
      id: 'template_breakfast',
      title: 'Healthy Breakfast',
      description: 'Eat a nutritious breakfast',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.forkKnife,
      color: const Color(0xFFE67E22),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['health', 'nutrition', 'breakfast'],
      suggestedReminderTime: '08:30',
    ),
    HabitTemplate(
      id: 'template_steps',
      title: '10,000 Steps',
      description: 'Reach daily step goal',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.footprints,
      color: const Color(0xFF00B894),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['health', 'walking', 'fitness'],
    ),
    HabitTemplate(
      id: 'template_no_sugar',
      title: 'No Added Sugar',
      description: 'Avoid processed sugars',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.forkKnife,
      color: const Color(0xFFE74C3C),
      difficulty: HabitDifficulty.hard,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 7,
      monthlyTarget: 30,
      tags: ['health', 'nutrition', 'diet'],
    ),
    HabitTemplate(
      id: 'template_cycling',
      title: 'Cycling',
      description: '30+ minutes of cycling',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.bicycle,
      color: const Color(0xFF3498DB),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 3,
      monthlyTarget: 12,
      tags: ['health', 'cycling', 'cardio'],
    ),
    HabitTemplate(
      id: 'template_swimming',
      title: 'Swimming',
      description: 'Swim for 30+ minutes',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.drop,
      color: const Color(0xFF00BCD4),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 2,
      monthlyTarget: 8,
      tags: ['health', 'swimming', 'cardio'],
    ),
    HabitTemplate(
      id: 'template_posture',
      title: 'Posture Check',
      description: 'Maintain good posture throughout the day',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.heart,
      color: const Color(0xFF95A5A6),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 7,
      monthlyTarget: 30,
      tags: ['health', 'posture', 'wellness'],
    ),
    HabitTemplate(
      id: 'template_screen_break',
      title: 'Screen Break',
      description: 'Take breaks from screens every hour',
      category: HabitCategory.health,
      icon: PhosphorIconsRegular.eye,
      color: const Color(0xFF7F8C8D),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['health', 'eye-care', 'wellness'],
    ),
    
    // Additional Productivity Habits
    HabitTemplate(
      id: 'template_email_zero',
      title: 'Email Zero',
      description: 'Clear inbox to zero',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.envelope,
      color: const Color(0xFF3498DB),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['productivity', 'email', 'organization'],
      suggestedReminderTime: '09:00',
    ),
    HabitTemplate(
      id: 'template_pomodoro',
      title: 'Pomodoro Sessions',
      description: 'Complete 4 pomodoro sessions',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.timer,
      color: const Color(0xFFE74C3C),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['productivity', 'focus', 'time-management'],
    ),
    HabitTemplate(
      id: 'template_task_completion',
      title: 'Complete Top 3 Tasks',
      description: 'Finish your three most important tasks',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.checkCircle,
      color: const Color(0xFF2ECC71),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['productivity', 'tasks', 'priorities'],
      suggestedReminderTime: '08:00',
    ),
    HabitTemplate(
      id: 'template_declutter',
      title: 'Declutter Space',
      description: 'Organize and declutter for 15 minutes',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.house,
      color: const Color(0xFF95A5A6),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 3,
      monthlyTarget: 12,
      tags: ['productivity', 'organization', 'declutter'],
    ),
    HabitTemplate(
      id: 'template_no_social_media',
      title: 'No Social Media',
      description: 'Avoid social media during work hours',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.phone,
      color: const Color(0xFF34495E),
      difficulty: HabitDifficulty.hard,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['productivity', 'focus', 'distraction'],
    ),
    HabitTemplate(
      id: 'template_weekly_review',
      title: 'Weekly Review',
      description: 'Review week and plan ahead',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.calendar,
      color: const Color(0xFF9B59B6),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 1,
      monthlyTarget: 4,
      tags: ['productivity', 'planning', 'review'],
      suggestedReminderTime: '20:00',
    ),
    HabitTemplate(
      id: 'template_batch_processing',
      title: 'Batch Process Tasks',
      description: 'Group similar tasks together',
      category: HabitCategory.productivity,
      icon: PhosphorIconsRegular.clipboardText,
      color: const Color(0xFF3498DB),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 3,
      monthlyTarget: 12,
      tags: ['productivity', 'efficiency', 'organization'],
    ),
    
    // Additional Learning Habits
    HabitTemplate(
      id: 'template_read_article',
      title: 'Read Article',
      description: 'Read one educational article',
      category: HabitCategory.learning,
      icon: PhosphorIconsRegular.bookOpen,
      color: const Color(0xFF3498DB),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['learning', 'reading', 'education'],
    ),
    HabitTemplate(
      id: 'template_podcast',
      title: 'Listen to Podcast',
      description: 'Listen to educational podcast',
      category: HabitCategory.learning,
      icon: PhosphorIconsRegular.microphone,
      color: const Color(0xFFE67E22),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 4,
      monthlyTarget: 16,
      tags: ['learning', 'podcast', 'education'],
    ),
    HabitTemplate(
      id: 'template_vocabulary',
      title: 'Learn 5 New Words',
      description: 'Expand your vocabulary',
      category: HabitCategory.learning,
      icon: PhosphorIconsRegular.translate,
      color: const Color(0xFF1ABC9C),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['learning', 'vocabulary', 'language'],
    ),
    HabitTemplate(
      id: 'template_skill_practice',
      title: 'Practice Skill',
      description: 'Dedicate time to skill development',
      category: HabitCategory.learning,
      icon: PhosphorIconsRegular.target,
      color: const Color(0xFF8E44AD),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 4,
      monthlyTarget: 16,
      tags: ['learning', 'skills', 'development'],
    ),
    HabitTemplate(
      id: 'template_ted_talk',
      title: 'Watch TED Talk',
      description: 'Watch an inspiring TED talk',
      category: HabitCategory.learning,
      icon: PhosphorIconsRegular.videoCamera,
      color: const Color(0xFFE74C3C),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 2,
      monthlyTarget: 8,
      tags: ['learning', 'inspiration', 'education'],
      suggestedReminderTime: '19:00',
    ),
    HabitTemplate(
      id: 'template_note_taking',
      title: 'Take Notes',
      description: 'Write notes on what you learned',
      category: HabitCategory.learning,
      icon: PhosphorIconsRegular.notebook,
      color: const Color(0xFF34495E),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['learning', 'notes', 'retention'],
    ),
    HabitTemplate(
      id: 'template_research',
      title: 'Research Topic',
      description: 'Deep dive into a topic of interest',
      category: HabitCategory.learning,
      icon: PhosphorIconsRegular.magnifyingGlass,
      color: const Color(0xFF3498DB),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 2,
      monthlyTarget: 8,
      tags: ['learning', 'research', 'knowledge'],
    ),
    
    // Additional Mindfulness Habits
    HabitTemplate(
      id: 'template_gratitude_journal',
      title: 'Gratitude Journal',
      description: 'Write 3 things you\'re grateful for',
      category: HabitCategory.mindfulness,
      icon: PhosphorIconsRegular.heart,
      color: const Color(0xFFE91E63),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 7,
      monthlyTarget: 30,
      tags: ['mindfulness', 'gratitude', 'positivity'],
      suggestedReminderTime: '20:30',
    ),
    HabitTemplate(
      id: 'template_nature_walk',
      title: 'Nature Walk',
      description: 'Spend time in nature mindfully',
      category: HabitCategory.mindfulness,
      icon: PhosphorIconsRegular.tree,
      color: const Color(0xFF27AE60),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 3,
      monthlyTarget: 12,
      tags: ['mindfulness', 'nature', 'peace'],
    ),
    HabitTemplate(
      id: 'template_digital_detox',
      title: 'Digital Detox Hour',
      description: 'Unplug from devices for one hour',
      category: HabitCategory.mindfulness,
      icon: PhosphorIconsRegular.moon,
      color: const Color(0xFF34495E),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['mindfulness', 'detox', 'wellness'],
      suggestedReminderTime: '19:00',
    ),
    HabitTemplate(
      id: 'template_body_scan',
      title: 'Body Scan Meditation',
      description: '10-minute body awareness practice',
      category: HabitCategory.mindfulness,
      icon: PhosphorIconsRegular.heart,
      color: const Color(0xFF9B59B6),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 4,
      monthlyTarget: 16,
      tags: ['mindfulness', 'meditation', 'awareness'],
      suggestedReminderTime: '21:00',
    ),
    HabitTemplate(
      id: 'template_loving_kindness',
      title: 'Loving Kindness',
      description: 'Practice loving-kindness meditation',
      category: HabitCategory.mindfulness,
      icon: PhosphorIconsRegular.heart,
      color: const Color(0xFFE91E63),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 3,
      monthlyTarget: 12,
      tags: ['mindfulness', 'compassion', 'meditation'],
    ),
    HabitTemplate(
      id: 'template_mindful_eating',
      title: 'Mindful Eating',
      description: 'Eat without distractions',
      category: HabitCategory.mindfulness,
      icon: PhosphorIconsRegular.forkKnife,
      color: const Color(0xFFF39C12),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['mindfulness', 'eating', 'awareness'],
    ),
    
    // Additional Creativity Habits
    HabitTemplate(
      id: 'template_photography',
      title: 'Take a Photo',
      description: 'Capture something beautiful',
      category: HabitCategory.creativity,
      icon: PhosphorIconsRegular.camera,
      color: const Color(0xFF3498DB),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['creativity', 'photography', 'art'],
    ),
    HabitTemplate(
      id: 'template_doodle',
      title: 'Doodle or Sketch',
      description: 'Free-form creative expression',
      category: HabitCategory.creativity,
      icon: PhosphorIconsRegular.pencilSimple,
      color: const Color(0xFFE74C3C),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 4,
      monthlyTarget: 16,
      tags: ['creativity', 'drawing', 'art'],
    ),
    HabitTemplate(
      id: 'template_sing',
      title: 'Sing or Hum',
      description: 'Express yourself through music',
      category: HabitCategory.creativity,
      icon: PhosphorIconsRegular.musicNote,
      color: const Color(0xFF9B59B6),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 5,
      monthlyTarget: 20,
      tags: ['creativity', 'music', 'expression'],
    ),
    HabitTemplate(
      id: 'template_craft',
      title: 'Creative Craft',
      description: 'Work on a creative project',
      category: HabitCategory.creativity,
      icon: PhosphorIconsRegular.palette,
      color: const Color(0xFFE67E22),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 3,
      monthlyTarget: 12,
      tags: ['creativity', 'craft', 'art'],
    ),
    HabitTemplate(
      id: 'template_poetry',
      title: 'Write Poetry',
      description: 'Express emotions through poetry',
      category: HabitCategory.creativity,
      icon: PhosphorIconsRegular.penNib,
      color: const Color(0xFF8E44AD),
      difficulty: HabitDifficulty.medium,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 2,
      monthlyTarget: 8,
      tags: ['creativity', 'poetry', 'writing'],
      suggestedReminderTime: '20:00',
    ),
    
    // Additional Wellness Habits
    HabitTemplate(
      id: 'template_skincare_routine',
      title: 'Skincare Routine',
      description: 'Complete morning and evening skincare',
      category: HabitCategory.wellness,
      icon: PhosphorIconsRegular.sparkle,
      color: const Color(0xFFFF6B9D),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 7,
      monthlyTarget: 30,
      tags: ['wellness', 'self-care', 'skincare'],
    ),
    HabitTemplate(
      id: 'template_face_mask',
      title: 'Face Mask',
      description: 'Weekly self-care face mask',
      category: HabitCategory.wellness,
      icon: PhosphorIconsRegular.sparkle,
      color: const Color(0xFFE91E63),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 1,
      monthlyTarget: 4,
      tags: ['wellness', 'self-care', 'skincare'],
      suggestedReminderTime: '21:00',
    ),
    HabitTemplate(
      id: 'template_bath',
      title: 'Relaxing Bath',
      description: 'Take time for a relaxing bath',
      category: HabitCategory.wellness,
      icon: PhosphorIconsRegular.wind, // wave icon doesn't exist, using wind
      color: const Color(0xFF00BCD4),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 2,
      monthlyTarget: 8,
      tags: ['wellness', 'self-care', 'relaxation'],
      suggestedReminderTime: '20:00',
    ),
    HabitTemplate(
      id: 'template_massage',
      title: 'Self Massage',
      description: '5 minutes of self-massage',
      category: HabitCategory.wellness,
      icon: PhosphorIconsRegular.heart,
      color: const Color(0xFFE91E63),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.evening,
      weeklyTarget: 3,
      monthlyTarget: 12,
      tags: ['wellness', 'self-care', 'relaxation'],
      suggestedReminderTime: '21:00',
    ),
    HabitTemplate(
      id: 'template_affirmations',
      title: 'Daily Affirmations',
      description: 'Repeat positive affirmations',
      category: HabitCategory.wellness,
      icon: PhosphorIconsRegular.heart,
      color: const Color(0xFFF39C12),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.morning,
      weeklyTarget: 7,
      monthlyTarget: 30,
      tags: ['wellness', 'self-care', 'positivity'],
      suggestedReminderTime: '08:00',
    ),
    HabitTemplate(
      id: 'template_social_connection',
      title: 'Social Connection',
      description: 'Connect with a friend or family',
      category: HabitCategory.wellness,
      icon: PhosphorIconsRegular.users,
      color: const Color(0xFF3498DB),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 3,
      monthlyTarget: 12,
      tags: ['wellness', 'social', 'connection'],
    ),
    HabitTemplate(
      id: 'template_hobby_time',
      title: 'Hobby Time',
      description: 'Dedicate time to your hobby',
      category: HabitCategory.wellness,
      icon: PhosphorIconsRegular.star,
      color: const Color(0xFFF39C12),
      difficulty: HabitDifficulty.easy,
      timeBlock: HabitTimeBlock.anytime,
      weeklyTarget: 3,
      monthlyTarget: 12,
      tags: ['wellness', 'hobby', 'enjoyment'],
    ),
  ];

  /// Get templates by category
  static List<HabitTemplate> getByCategory(HabitCategory category) {
    return all.where((t) => t.category == category).toList();
  }

  /// Search templates by keyword
  static List<HabitTemplate> search(String query) {
    final lowerQuery = query.toLowerCase();
    return all.where((t) {
      return t.title.toLowerCase().contains(lowerQuery) ||
          t.description.toLowerCase().contains(lowerQuery) ||
          t.tags.any((tag) => tag.toLowerCase().contains(lowerQuery));
    }).toList();
  }

  /// Get popular templates (most commonly used)
  static List<HabitTemplate> getPopular() {
    return [
      all.firstWhere((t) => t.id == 'template_water'),
      all.firstWhere((t) => t.id == 'template_exercise'),
      all.firstWhere((t) => t.id == 'template_reading'),
      all.firstWhere((t) => t.id == 'template_meditation'),
      all.firstWhere((t) => t.id == 'template_journal'),
    ];
  }
}

